### ISSUE TITLE
Socket connection slow, then no further data.

### ISSUE THREAD

**Issue by sauropodlet** [JKorf/Bittrex.Net#85] opened 2018-04-05 18:25 UTC
@JKorf Thanks for the great library and the speedy release. I'm on 2.1.0.

If I call SubscribeToExchangeStateUpdatesAsync for multiple pairs, after a while (within 20 minutes) I get a slow connection warning and data stops arriving completely, without recovery.

2018/04/05 07:09:46:686 | Warning | Socket connection slow

I'm pretty sure this is new behaviour with the 2.1 release.

Currently I'm manually restarting my application (console, regular .net framework 4.7), and this is working flawlessly.

Is there some way I can capture the transition to this state so I can restart the BittrexSocketClient in code?

Thanks for your work and your time.

**Comment by pwnzya** [comment] 2018-04-05 19:28
Hello.

Just wanted to tell you that the behavior you described was reported previously (check #82 and where it's referenced), and v2.1.0 supposedly fixed it.
I am currently testing SubscribeToExchangeStateUpdatesAsync myself (running 4 pairs simultaneously.)

Are you sure you are using Bittrex.Net v2.1.0, and not v2.0.10?
I'll report back here if the behavior happens in my test runs.

**Comment by sauropodlet** [comment] 2018-04-05 19:51
I'm definitely on 2.1.0.

**Comment by sauropodlet** [comment] 2018-04-05 20:02
I'm calling SubscribeToExchangeStateUpdatesAsync for all pairs, i.e. for every market on Bittrex. Perhaps this is a lot to ask of a websocket, but it has been working for a month until last night (22:00 UTC). I updated the library when it was released and have observed this new issue on each run since then.

**Comment by pwnzya** [comment] 2018-04-05 20:27
I see.
Just curious; have you tried creating a separate instance of websocket client for each market?

**Comment by JKorf** [comment] 2018-04-06 06:26
I'll see if I can reproduce this, thanks for letting me know. @pwnzya It doesn't really matter if he uses a single websocket client or a new one for each since under the hood it will use a single socket ;)

**Comment by pwnzya** [comment] 2018-04-06 06:52
Update on my test runs:

One of the four subscriptions of SubscribeToExchangeStateUpdatesAsync in my test run stopped receiving data about an hour ago. (after a total run time of aprox. 15 hours)
It's last logged message was "Socket connection slow" warning message.
This behavior is similar to the previous reports, however, my app CAN reconnect to the same market if I manually hit Disconnect button and then Connect button - my app couldn't do that with v2.0.10.
That's certainly an improvement I see in v2.1.0 over v2.0.10.

* I was running four separate instances of my little test app, each subscribing to different market.

**Comment by JKorf** [comment] 2018-04-06 06:54
Thanks for the update. So there seems to be a problem where data stops coming in but we never actually disconnect, so also never reconnect.

**Comment by sauropodlet** [comment] 2018-04-06 13:53
I'll have a go with 2.1.1 and will post my results here.

**Comment by JKorf** [comment] 2018-04-06 13:58
I've found the issue I think, it should be fixed in the new version, v2.1.1. Please let me know if it (doesn't) work.

**Comment by sauropodlet** [comment] 2018-04-07 02:25
I've had 9 hours uptime. It looks like it's fixed. Thanks again.

**Comment by JKorf** [comment] 2018-04-07 07:03
Great, I'll close this issue then. Let me know if anything comes up

**Closed by JKorf** 2018-04-07 07:03 UTC
