### ISSUE TITLE
Websocket unresponsive 

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Bittrex.Net#67] opened 2018-02-19 07:13 UTC
Dim client = New BittrexSocketClient()
        client.SetApiCredentials(BtxApiKeyTB.Text, BtxApiSecretTB.Text)
        client.CloudFlareRetries = 99
        client.SetLogOutput(Console.Out)
        'client.ConnectionFactory.
        Dim subcribtionSuccess = client.SubscribeToMarketDeltaStream("BTC-ETH", Function(data)
                                                                                    MsgBox(data.Ask)
                                                                                End Function)
        If subcribtionSuccess.Success Then
            BtxWriteLog(subcribtionSuccess.Success)
        Else
            BtxWriteLog(subcribtionSuccess.Error.ErrorMessage)
        End If

The websocket does nothing at all like it used to. No error message either, it just freezes.
Im assuming it somthing on Bittrex sever side, but wondering if anyone had any ideas.

**Comment by JKorf** [comment] 2018-02-19 08:27
Hi, should be fixed in the latest version. After doing some rework some .ConfigureAwait(false) calls were forgotten, causing things to freeze up when called from a UI thread.

**Comment by Cjay93** [comment] 2018-02-19 16:38
Thanks man your brilliant

**Comment by Cjay93** [comment] 2018-02-19 18:50
It still seems to just not return anthing, shows no errors.

**Comment by JKorf** [comment] 2018-02-20 08:43
I can't reproduce the issue. Are you using 1.3.11? What does the log output say?

**Comment by Cjay93** [comment] 2018-02-20 15:22
Yes im using the latest release.

`Dim NewTask = Task.Factory.StartNew(Sub()

                                                Dim client = New BittrexSocketClient()
                                                client.SetLogOutput(Console.Out)
                                                Dim subcribtionSuccess = client.SubscribeToMarketDeltaStream("BTC-XVG", Sub(Data)
                                                                                                                            BtxWriteLog(Data.High.Value)
                                                                                                                            BtxWriteLog(Data.MarketName)
                                                                                                                        End Sub)

                                          

                                            End Sub)`
has not output or result, so weird.

**Comment by JKorf** [comment] 2018-02-20 15:23
Can you add client.SetLogVerbosity(LogVerbosity.Debug) and see if that brings up anything?

**Comment by Cjay93** [comment] 2018-02-20 15:29
=== Pre-bind state information ===
LOG: DisplayName = System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///$$/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.AspNet.SignalR.Client, Version=2.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\$$$\bin\Debug\$$.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 4.1.1.2.
LOG: Post-policy reference: System.Net.Http, Version=4.1.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Users/Admin/source/repos/DXApplication3/DXApplication3/bin/Debug/System.Net.Http.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.Initialize(IConnection connection)
   at Bittrex.Net.Sockets.HttpClientWithUserAgent.Initialize(IConnection connection)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetNegotiationResponse(IHttpClient httpClient, IConnection connection, String connectionData)
   at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.Negotiate(IConnection connection, String connectionData)
   at Microsoft.AspNet.SignalR.Client.Connection.Negotiate(IClientTransport transport)
   at Microsoft.AspNet.SignalR.Client.Connection.Start(IClientTransport transport)
   at Bittrex.Net.Sockets.BittrexHubConnection.Start()
   at Bittrex.Net.BittrexSocketClient.<TryStart>d__49.MoveNext()

**Comment by Cjay93** [comment] 2018-02-20 15:58
any idea Jkorf of the correct way to fix this.

**Comment by JKorf** [comment] 2018-02-21 10:34
Can you try to remove the System.Net.Http reference from your project and retry?

**Comment by Cjay93** [comment] 2018-02-21 15:48
Yeah removed it and just tested it, now its finally connecting but only after failure so takes a long time to connect and is very slow compared to binance websocket(not saying its your wrapper).

10:46:02:703 | Debug | Going to subscribe to BTC-ETH
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\Microsoft.AspNet.SignalR.Client.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
10:46:02:719 | Debug | Starting connection to bittrex server
10:46:02:759 | Debug | Socket state: Disconnected -> Connecting
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.WebRequest\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.WebRequest.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
10:46:03:225 | Debug | Socket state: Connecting -> Disconnected
10:46:03:232 | Debug | Socket closed
10:46:03:240 | Debug | Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: close
  X-Frame-Options: SAMEORIGIN
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 3f0ad5fd9ee18395-BKK
  Cache-Control: no-cache
  Date: Wed, 21 Feb 2018 15:45:59 GMT
  Set-Cookie: __cfduid=da36a26708680459f7c4ccb6cbe4b72bc1519227959; expires=Thu, 21-Feb-19 15:45:59 GMT; path=/; domain=.bittrex.com; HttpOnly
  Server: cloudflare
  Content-Type: text/html; charset=UTF-8
}
   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass5_0.<Get>b__1(HttpResponseMessage responseMessage)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3_0.<RunTask>b__0(Task`1 t)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Bittrex.Net.BittrexSocketClient.<TryStart>d__49.MoveNext()
10:46:03:241 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\CloudFlareUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Threading.Tasks.dll'. Cannot find or open the PDB file.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Net.Primitives.dll'. Cannot find or open the PDB file.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Runtime.dll'. Cannot find or open the PDB file.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Linq.dll'. Cannot find or open the PDB file.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Collections.dll'. Cannot find or open the PDB file.
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\System.Text.RegularExpressions.dll'. Cannot find or open the PDB file.
10:46:09:584 | Debug | CloudFlare cookies retrieved, retrying connection
10:46:09:584 | Debug | Socket state: Disconnected -> Connecting
'BitLite.exe' (CLR v4.0.30319: BitLite.exe): Loaded 'C:\Users\Admin\source\repos\DXApplication3\DXApplication3\bin\Debug\websocket-sharp-customheaders.dll'. Cannot find or open the PDB file.
10:46:12:506 | Debug | Socket state: Connecting -> Connected
The thread 0xa04 has exited with code 0 (0x0).
The thread 0x426c has exited with code 0 (0x0).

**Comment by JKorf** [comment] 2018-02-21 17:05
That's as expected, can't change much about that. The biggest time consumer is getting passed the CloudFlare protection which takes a couple of seconds. Can't speed that up sadly. Glad you got it working though.

**Closed by JKorf** 2018-02-21 17:05 UTC
